variable "resource_group_name" {}
variable "resource_group_name_location" {}
variable "cluster_name" {}
variable "vm_size" {}
variable "max_count" {}
variable "min_count" {}
variable "client_id" {}
variable "client_secret" {}
variable "environment" {}
variable "node_pool_name" {}
variable "kubernetes_version" {}
variable "username" {}